### ISSUE TITLE
Update Documentation on Configuring Cluster Mode Enabled Redis Clusters

### ISSUE THREAD

**Issue by YungBinary** [OpenCTI-Platform/docs#22]
Configuring cluster mode enabled Redis clusters could be more-well documented, to get the community up and running faster with OpenCTI and for users of OpenCTI to receive the benefits of using a cluster mode enabled Redis cluster. Using the cluster configuration endpoint is a more suited alternative to specifying individual cache nodes in the config.

The following JSON represents the variables and values needed in order to setup a cluster mode enabled cluster with the cluster's configuration endpoint, supported by OpenCTI's existing code-base. Note: Several of these configuration parameters require that the cluster has **Encryption in transit** enabled and **Transit encryption mode** required. Specifically, the REDIS__USE_SSL variable needs to be set to true and the REDIS__CA variable as shown below. I think it would be worthwhile for all of this to be documented, as well as documenting the required configuration variables for users not using encryption/SSL for their cluster.

```
    "REDIS__HOSTNAME": "clustercfg.example-cluster.xxxxxx.use1.cache.amazonaws.com"
    "REDIS__HOSTNAMES": "[\"clustercfg.example-cluster.xxxxxx.use1.cache.amazonaws.com:6379\"]",
    "REDIS__PORT": "6379",
    "REDIS__CA": "[\"/etc/ssl/certs/ca-certificates.crt\"]",
    "REDIS__USE_SSL": "true",
    "REDIS__MODE": "cluster",
    "REDIS__USERNAME": "<username>",
    "REDIS__PASSWORD": "<password>"
```

**Comment by SamuelHassine** [comment]
Hello @YungBinary,

Done here: https://docs.opencti.io/5.7.X/deployment/clustering/#redis.

Kind regards,
Samuel
